config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib.staticfiles.urls import static
# from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orikomi.urls')),
    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orikomi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from orikomi.views import IndexView, InquiryView, MenuView, OrikomiDetailView, \
    OrikomiCreateView, OrikomiUpdatelView, OrikomiDeleteView, OrikomiSearchView

app_name = 'orikomi'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('inquiry/', InquiryView.as_view(), name='inquiry'),
    path('menu/', MenuView.as_view(), name='menu'),
    path('orikomi_detail/<int:pk>/', OrikomiDetailView.as_view(), name='orikomi_detail'),
    path('orikomi_create/', OrikomiCreateView.as_view(), name='orikomi_create'),
    path('orikomi_update/<int:pk>/', OrikomiUpdatelView.as_view(), name='orikomi_update'),
    path('orikomi_delete/<int:pk>/', OrikomiDeleteView.as_view(), name='orikomi_delete'),
    path('orikomi_search/', OrikomiSearchView.as_view(), name='orikomi_search'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orikomi/models.py
from accounts.models import CustomUser
from django.db import models


class Area(models.Model):
    # 上演地域用DB。area_jpは可読性のある表記用カラム
    area = models.CharField(verbose_name='上演地域(DB値)', max_length=30, primary_key=True)
    area_jp = models.CharField(verbose_name='上演地域(web上表記)', max_length=30)

    class Meta:
        verbose_name_plural='area'
    # area_jpを返し、ユーザが読めるようにする。
    def __str__(self):
        return self.area_jp


class Genre(models.Model):
    genre = models.CharField(verbose_name='ジャンル（DB値）', max_length=30, primary_key=True)
    genre_jp = models.CharField(verbose_name='ジャンル（web上表記）', max_length=30)

    class Meta:
        verbose_name_plural='genre'

    def __str__(self):
        return self.genre_jp


class Orikomi(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='公演名', max_length=150)
    start_day = models.DateField(verbose_name='上演開始日')
    end_day = models.DateField(verbose_name='上演終了日')
    area = models.ForeignKey(Area, verbose_name='上演地域', to_field='area', on_delete=models.PROTECT)
    genre = models.ForeignKey(Genre, verbose_name='ジャンル', to_field='genre', on_delete=models.PROTECT)
    front_imege = models.ImageField(verbose_name='チラシ表面')
    back_image = models.ImageField(verbose_name='チラシ裏面', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural='orikomi'

    def __str__(self):
        return self.title

templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- My Style -->
    <link href="{% static 'base_style.css' %}" rel="stylesheet" type="text/css">

    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light py-3" style="background-color: #fff338;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'orikomi:index' %}">orikomi</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'orikomi:orikomi_search' %}">オリコミをみる</a>
            <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
            <a class="nav-link" href="{% url 'orikomi:inquiry' %}">お問い合わせ</a>
          </div>
        </div>
      </div>
    </nav>


    {% block header %}{% endblock header %}
    {% block content %}{% endblock content %}

    <footer class="footer mt-auto py-3 fixed-bottom" style="background-color: #fff338;">
      <div class="container">
        <span class="text-muted">Copyright (C) 2021 orikomi All Rights Reserved.</span>
      </div>
    </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<main class="px-3">
    <div class="container py-5">
        <h1 class="text-center">orikomi</h1>
        <div class="d-grid gap-2 col-6 mx-auto mt-5">
            <h5>オリコミを見たい方</h3>
            <a class="btn btn-outline-secondary" href="{% url 'orikomi:orikomi_search' %}" role="button">オリコミを見る</a>
            <h5 class="mt-5">オリコミをしたい方</h3>
            <a class="btn btn-outline-secondary" href="{% url 'account_signup' %}" role="button">ユーザー登録</a>
            <a class="btn btn-outline-secondary" href="{% url 'account_login' %}" role="button">ログイン</a>
            <a class="btn btn-outline-secondary" href="{% url 'orikomi:menu' %}" role="button">メニュー</a>
            <h5 class="mt-5">お問い合わせ</h3>
            <a class="btn btn-outline-secondary" href="{% url 'orikomi:inquiry' %}" role="button">お問い合わせフォーム</a>
        </div>
    </div>
</main>
{% endblock content %}

templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ{% endblock title %}

{% block content %}

<main class="px-3">
    <h2 class="text-center py-5">お問い合わせフォーム</h2>
    {% if messages %}
        {% for message in messages %}
        <div class="container text-center">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    <div class="container mt-2">
        <form method="post">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for field in form %}
            <div class="col-sm-12">
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <div class="d-grid gap-2 col-6 mx-auto mt-3">
                <button class="btn btn-outline-secondary" type="submit">送信</button>
            </div>
        </form>
    </div>
</main>
{% endblock content %}

templates/menu.html
{% extends 'base.html' %}

{% block content %}
<main class="px-3">
  <div class="container py-5">
    <h1 class="text-center">ログイン後メニュー</h1>
    <div class="text-center mt-3">
      <span><a class="btn btn-outline-secondary" href="{% url 'orikomi:orikomi_create' %}" role="button">オリコミする</a></span>
      <span><a class="btn btn-outline-secondary" href="{% url 'account_logout' %}" role="button">ログアウト</a></span>
    </div>
    <div class="card-deck mt-3">
      <div class="row">
        {% for item in object_list %}
        <div class="col-sm-4 py-2">
          <div class="card h-100">
            <img src="{{ item.front_imege.url }}" alt="front_image" class="card-img-top" >
            <div class="card-body">
              <p class="card-text"><a href="{% url 'orikomi:orikomi_detail' item.pk %}">公演名：{{ item.title }}</a></p>
              <p class="card-text">上演日：{{ item.start_day }}〜{{ item.end_day }}</p>
            </div>
          </div>
        </div>

        {% empty %}
        <p class="text-center mt-5">折り込みがありません。</p>
        {% endfor %}
      </div>
    </div>

    {% include "paginate.html" %}

  </div>
</main>
{% endblock content %}

templates/orikomi_create.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
        {{ form.as_table }}
    </table>
    <button class="btn btn-primary" type="submit">オリコミする</button>
</form>
{% endblock content %}

templates/orikomi_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>本当に削除しますか？</p>
    <button class="btn btn-primary" type="submit">削除</button>
    <a class="btn btn-secondary" href="{% url 'orikomi:orikomi_detail' object.pk %}">キャンセル</a>
</form>

{% endblock content %}

templates/orikomi_detail.html
{% extends 'base.html' %}

{% block content %}

<p>公演名：{{ object.title }}</p>
<p>上演日：{{ object.start_day }}〜{{ object.end_day }}</p>
<p>上演地域：{{ object.area.get_area_display }}</p>
<p>ジャンル：{{ object.genre.get_genre_display }}</p>
<p>チラシ表面</p>
<img src="{{ object.front_imege.url }}" alt="front_image">
{% if object.back_image %}
<p>チラシ裏面</p>
<img src="{{ object.back_image.url }}" alt="back_imege">
{% endif %}
<p>{{ object.created_at }}</p>

<p><a href="{% url 'orikomi:orikomi_update' object.pk %}">編集</a></p>
<p><a href="{% url 'orikomi:orikomi_delete' object.pk %}">削除</a></p>

{% endblock content %}

templates/orikomi_search.html
{% extends 'base.html' %}

{% block content %}

<form method="get" value="{{request.GET.q}}" action="{% url 'orikomi:orikomi_search' %}">
    <div class="tmodel-body">
        {{ OrikomiSearchForm.as_p }}
    </div>
    <button class="btn btn-primary" type="submit" >検索</button>
</form>

{% for item in object_list %}
<p>公演名：{{ item.title }}</p>
<p><img src="{{ item.front_imege.url }}" alt="front_image"></p>
{% empty %}
<p>対象のデータがありません</p>
{% endfor %}


{% endblock content %}

templates/orikomi_update.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
        {{ form.as_table }}
    </table>
    <button class="btn btn-primary" type="submit">更新する</button>
    <a class="btn btn-secondary" href="{% url 'orikomi:orikomi_detail' object.pk %}">キャンセル</a>
</form>

{% endblock content %}

templates/paginate.html
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center mt-2">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">前へ</span>
      </a>
    </li>
    {% endif %}

    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
      <a class="page-link">
        {{ num }}
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">次へ</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}